// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: baselines.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteBaselineByName = `-- name: DeleteBaselineByName :execrows
DELETE FROM baselines
WHERE workspace_id = $1 AND name = $2
`

type DeleteBaselineByNameParams struct {
	WorkspaceID uuid.UUID
	Name        string
}

func (q *Queries) DeleteBaselineByName(ctx context.Context, arg DeleteBaselineByNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBaselineByName, arg.WorkspaceID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBaselineByName = `-- name: GetBaselineByName :one
SELECT id, workspace_id, name, pack_version_id, run_id, scorecard_snapshot, created_at, updated_at
FROM baselines
WHERE workspace_id = $1 AND name = $2
LIMIT 1
`

type GetBaselineByNameParams struct {
	WorkspaceID uuid.UUID
	Name        string
}

func (q *Queries) GetBaselineByName(ctx context.Context, arg GetBaselineByNameParams) (Baseline, error) {
	row := q.db.QueryRow(ctx, getBaselineByName, arg.WorkspaceID, arg.Name)
	var i Baseline
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.PackVersionID,
		&i.RunID,
		&i.ScorecardSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBaselinesByWorkspace = `-- name: ListBaselinesByWorkspace :many
SELECT id, workspace_id, name, pack_version_id, run_id, scorecard_snapshot, created_at, updated_at
FROM baselines
WHERE workspace_id = $1
ORDER BY updated_at DESC, name ASC
`

type ListBaselinesByWorkspaceParams struct {
	WorkspaceID uuid.UUID
}

func (q *Queries) ListBaselinesByWorkspace(ctx context.Context, arg ListBaselinesByWorkspaceParams) ([]Baseline, error) {
	rows, err := q.db.Query(ctx, listBaselinesByWorkspace, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Baseline
	for rows.Next() {
		var i Baseline
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.PackVersionID,
			&i.RunID,
			&i.ScorecardSnapshot,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBaseline = `-- name: UpsertBaseline :one
INSERT INTO baselines (
    workspace_id,
    name,
    pack_version_id,
    run_id,
    scorecard_snapshot
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (workspace_id, name) DO UPDATE SET
    pack_version_id = EXCLUDED.pack_version_id,
    run_id = EXCLUDED.run_id,
    scorecard_snapshot = EXCLUDED.scorecard_snapshot,
    updated_at = now()
RETURNING id, workspace_id, name, pack_version_id, run_id, scorecard_snapshot, created_at, updated_at
`

type UpsertBaselineParams struct {
	WorkspaceID       uuid.UUID
	Name              string
	PackVersionID     uuid.UUID
	RunID             uuid.UUID
	ScorecardSnapshot []byte
}

// Save or replace a named baseline within a workspace. Same-name re-publish
// overwrites — baselines are moving bookmarks by design (users retrain
// "main" when their challenge pack evolves).
func (q *Queries) UpsertBaseline(ctx context.Context, arg UpsertBaselineParams) (Baseline, error) {
	row := q.db.QueryRow(ctx, upsertBaseline,
		arg.WorkspaceID,
		arg.Name,
		arg.PackVersionID,
		arg.RunID,
		arg.ScorecardSnapshot,
	)
	var i Baseline
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.PackVersionID,
		&i.RunID,
		&i.ScorecardSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
