// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scan_findings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countScanFindingsBySeverity = `-- name: CountScanFindingsBySeverity :many
SELECT severity, count(*)::bigint AS n
FROM scan_findings
WHERE eval_set_id = $1
GROUP BY severity
ORDER BY severity
`

type CountScanFindingsBySeverityParams struct {
	EvalSetID uuid.UUID
}

type CountScanFindingsBySeverityRow struct {
	Severity string
	N        int64
}

func (q *Queries) CountScanFindingsBySeverity(ctx context.Context, arg CountScanFindingsBySeverityParams) ([]CountScanFindingsBySeverityRow, error) {
	rows, err := q.db.Query(ctx, countScanFindingsBySeverity, arg.EvalSetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountScanFindingsBySeverityRow
	for rows.Next() {
		var i CountScanFindingsBySeverityRow
		if err := rows.Scan(&i.Severity, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScanFindingByID = `-- name: GetScanFindingByID :one
SELECT id, workspace_id, organization_id, eval_set_id, case_result_id, matrix_key, case_key, scanner, scanner_version, severity, category, evidence, confidence, status, status_updated_by, status_updated_at, created_at, updated_at FROM scan_findings WHERE id = $1
`

type GetScanFindingByIDParams struct {
	ID uuid.UUID
}

func (q *Queries) GetScanFindingByID(ctx context.Context, arg GetScanFindingByIDParams) (ScanFinding, error) {
	row := q.db.QueryRow(ctx, getScanFindingByID, arg.ID)
	var i ScanFinding
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OrganizationID,
		&i.EvalSetID,
		&i.CaseResultID,
		&i.MatrixKey,
		&i.CaseKey,
		&i.Scanner,
		&i.ScannerVersion,
		&i.Severity,
		&i.Category,
		&i.Evidence,
		&i.Confidence,
		&i.Status,
		&i.StatusUpdatedBy,
		&i.StatusUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScanFindingsByEvalSetID = `-- name: ListScanFindingsByEvalSetID :many
SELECT id, workspace_id, organization_id, eval_set_id, case_result_id, matrix_key, case_key, scanner, scanner_version, severity, category, evidence, confidence, status, status_updated_by, status_updated_at, created_at, updated_at FROM scan_findings
WHERE eval_set_id = $1
  AND ($2::text IS NULL OR severity = $2)
  AND ($3::text IS NULL OR status = $3)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListScanFindingsByEvalSetIDParams struct {
	EvalSetID   uuid.UUID
	Severity    *string
	Status      *string
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) ListScanFindingsByEvalSetID(ctx context.Context, arg ListScanFindingsByEvalSetIDParams) ([]ScanFinding, error) {
	rows, err := q.db.Query(ctx, listScanFindingsByEvalSetID,
		arg.EvalSetID,
		arg.Severity,
		arg.Status,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanFinding
	for rows.Next() {
		var i ScanFinding
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.OrganizationID,
			&i.EvalSetID,
			&i.CaseResultID,
			&i.MatrixKey,
			&i.CaseKey,
			&i.Scanner,
			&i.ScannerVersion,
			&i.Severity,
			&i.Category,
			&i.Evidence,
			&i.Confidence,
			&i.Status,
			&i.StatusUpdatedBy,
			&i.StatusUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScanFindingStatus = `-- name: UpdateScanFindingStatus :one
UPDATE scan_findings
SET status = $1,
    status_updated_by = $2,
    status_updated_at = now(),
    updated_at = now()
WHERE id = $3
RETURNING id, workspace_id, organization_id, eval_set_id, case_result_id, matrix_key, case_key, scanner, scanner_version, severity, category, evidence, confidence, status, status_updated_by, status_updated_at, created_at, updated_at
`

type UpdateScanFindingStatusParams struct {
	Status          string
	StatusUpdatedBy *uuid.UUID
	ID              uuid.UUID
}

func (q *Queries) UpdateScanFindingStatus(ctx context.Context, arg UpdateScanFindingStatusParams) (ScanFinding, error) {
	row := q.db.QueryRow(ctx, updateScanFindingStatus, arg.Status, arg.StatusUpdatedBy, arg.ID)
	var i ScanFinding
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OrganizationID,
		&i.EvalSetID,
		&i.CaseResultID,
		&i.MatrixKey,
		&i.CaseKey,
		&i.Scanner,
		&i.ScannerVersion,
		&i.Severity,
		&i.Category,
		&i.Evidence,
		&i.Confidence,
		&i.Status,
		&i.StatusUpdatedBy,
		&i.StatusUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertScanFinding = `-- name: UpsertScanFinding :one
INSERT INTO scan_findings (
    workspace_id,
    organization_id,
    eval_set_id,
    case_result_id,
    matrix_key,
    case_key,
    scanner,
    scanner_version,
    severity,
    category,
    evidence,
    confidence,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
ON CONFLICT (eval_set_id, case_key, scanner, scanner_version) DO UPDATE SET
    severity = EXCLUDED.severity,
    category = EXCLUDED.category,
    evidence = EXCLUDED.evidence,
    confidence = EXCLUDED.confidence,
    case_result_id = COALESCE(EXCLUDED.case_result_id, scan_findings.case_result_id),
    updated_at = now()
RETURNING id, workspace_id, organization_id, eval_set_id, case_result_id, matrix_key, case_key, scanner, scanner_version, severity, category, evidence, confidence, status, status_updated_by, status_updated_at, created_at, updated_at
`

type UpsertScanFindingParams struct {
	WorkspaceID    uuid.UUID
	OrganizationID uuid.UUID
	EvalSetID      uuid.UUID
	CaseResultID   *uuid.UUID
	MatrixKey      string
	CaseKey        string
	Scanner        string
	ScannerVersion string
	Severity       string
	Category       string
	Evidence       string
	Confidence     float64
	Status         string
}

func (q *Queries) UpsertScanFinding(ctx context.Context, arg UpsertScanFindingParams) (ScanFinding, error) {
	row := q.db.QueryRow(ctx, upsertScanFinding,
		arg.WorkspaceID,
		arg.OrganizationID,
		arg.EvalSetID,
		arg.CaseResultID,
		arg.MatrixKey,
		arg.CaseKey,
		arg.Scanner,
		arg.ScannerVersion,
		arg.Severity,
		arg.Category,
		arg.Evidence,
		arg.Confidence,
		arg.Status,
	)
	var i ScanFinding
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OrganizationID,
		&i.EvalSetID,
		&i.CaseResultID,
		&i.MatrixKey,
		&i.CaseKey,
		&i.Scanner,
		&i.ScannerVersion,
		&i.Severity,
		&i.Category,
		&i.Evidence,
		&i.Confidence,
		&i.Status,
		&i.StatusUpdatedBy,
		&i.StatusUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
