// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const backfillUserEmail = `-- name: BackfillUserEmail :one
UPDATE users
SET
    email = CASE
        WHEN COALESCE(email, '') = '' AND $1::text <> '' THEN $1::text
        ELSE email
    END,
    updated_at = CASE
        WHEN COALESCE(email, '') = '' AND $1::text <> '' THEN now()
        ELSE updated_at
    END
WHERE id = $2 AND archived_at IS NULL
RETURNING id, workos_user_id, COALESCE(email, '') AS email, COALESCE(display_name, '') AS display_name
`

type BackfillUserEmailParams struct {
	Email  string
	UserID uuid.UUID
}

type BackfillUserEmailRow struct {
	ID           uuid.UUID
	WorkosUserID string
	Email        string
	DisplayName  string
}

func (q *Queries) BackfillUserEmail(ctx context.Context, arg BackfillUserEmailParams) (BackfillUserEmailRow, error) {
	row := q.db.QueryRow(ctx, backfillUserEmail, arg.Email, arg.UserID)
	var i BackfillUserEmailRow
	err := row.Scan(
		&i.ID,
		&i.WorkosUserID,
		&i.Email,
		&i.DisplayName,
	)
	return i, err
}
